name: Hugo CI & deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and deploy website
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v3
       with:
         submodules: true
     - name: Setup Hugo
       uses: peaceiris/actions-hugo@v3
       with:
         hugo-version: 'latest'
         extended: true
     - name: Cache Dependencies
       uses: actions/cache@v4
       with:
         path: /home/runner/.cache/hugo_cache
         key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
         restore-keys: |
           ${{ runner.os }}-hugomod-
     - name: Run Node
       run: npm ci
     - name: Build website with Hugo
       run: hugo --minify --printI18Warnings
     - name: Deploy website with rsync
       uses: burnett01/rsync-deployments@5.2
       with:
         switches: -avzr --quiet --delete
         path: public/
         remote_path: ${{ secrets.DEPLOY_DIRECTORY }}
         remote_host: ${{ secrets.DEPLOY_HOST }}
         remote_user: ${{ secrets.DEPLOY_USER }}
         remote_key: ${{ secrets.DEPLOY_KEY }}
